server:
  port: 7005
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bali?charactorEncoding=UTF-8
    username: root
    password: ych13584734336
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: product-provider

eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress}
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7001/eureka

mybatis:
  type-aliases-package: cn.bdqn.bali.pojo
  mapper-locations: classpath:mapper/*Mapper.xml