server:
  port: 7003
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bali?charactorEncoding=UTF-8&useSSL=false
    username: root
    password: ych13584734336
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: user-provider

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7001/eureka

mybatis:
  type-aliases-package: cn.bdqn.bali.pojo
  mapper-locations: classpath:mapper/*Mapper.xml

